"use client"

// import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { GlobalProvider, useGlobalContext } from "@/context/context";
import { Suspense, useEffect } from "react";
import { useRouter } from "next/navigation";



const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const AuthChecker = ({ children }: { children: React.ReactNode }) => {
  const router = useRouter();
  const { isAuthenticated, loading } = useGlobalContext();

  useEffect(() => {
    if (!loading && !isAuthenticated && router.pathname !== '/login') {
      router.push('/login');
    }
  }, [loading, isAuthenticated, router]);

  return <>{children}</>;
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalProvider>
          <AuthChecker>
            <Suspense>{children}</Suspense>
          </AuthChecker>
        </GlobalProvider>
      </body>
    </html>
  );
}
